import { Trend, Production, Video, Platform, VideoDistribution, Comment, AnalyticsSnapshot } from './types';

export const mockTrends: Trend[] = [
  {
    id: '1',
    title: '5 AI Agents som gjor jobben din på 10 minutter',
    topic: 'AI Agents',
    platform: 'youtube',
    score: 94,
    status: 'pending',
    vinkling: 'Praktisk guide med live demonstrasjon av automatiseringsverktøy',
    tags: ['AI', 'Produktivitet', 'Automatisering'],
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: '2',
    title: 'Morning Routine Hack som sparer 2 timer hver dag',
    topic: 'Morning Hacks',
    platform: 'tiktok',
    score: 88,
    status: 'pending',
    vinkling: 'Personlig fortelling med før/etter sammenligning',
    tags: ['Produktivitet', 'Rutine', 'Livsstil'],
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: '3',
    title: 'ChatGPT gjør dette 1000x bedre enn Google',
    topic: 'ChatGPT vs Google',
    platform: 'youtube',
    score: 82,
    status: 'approved',
    vinkling: 'Direkte sammenligning med konkrete eksempler og resultater',
    tags: ['AI', 'ChatGPT', 'Tech'],
    created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: '4',
    title: 'Norske startups som tar verden med storm i 2025',
    topic: 'Norwegian Startups',
    platform: 'google',
    score: 76,
    status: 'pending',
    vinkling: 'Inspirerende historier med intervjuer og tall',
    tags: ['Startup', 'Norge', 'Business'],
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: '5',
    title: 'Disse 3 investerings-appene gjor meg rik på 6 måneder',
    topic: 'Investment Apps',
    platform: 'tiktok',
    score: 71,
    status: 'rejected',
    vinkling: 'Erfaringsbasert anmeldelse med faktiske tall og resultater',
    tags: ['Investering', 'Finans', 'Apps'],
    created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
  {
    id: '6',
    title: 'Slik bruker du Notion som en proff i 2025',
    topic: 'Notion Productivity',
    platform: 'youtube',
    score: 68,
    status: 'in_production',
    vinkling: 'Steg-for-steg opplæring med maler og eksempler',
    tags: ['Produktivitet', 'Notion', 'Verktøy'],
    created_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
  },
];

export const mockProductions: Production[] = [
  {
    id: 'p1',
    trend_id: '6',
    title: 'Slik bruker du Notion som en proff i 2025',
    status: 'editing',
    progress: 78,
    language: 'no',
    audience: 'produktivitets-entusiaster',
    error_message: null,
    script: null,
    created_at: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: 'p2',
    trend_id: '3',
    title: 'ChatGPT gjør dette 1000x bedre enn Google',
    status: 'recording',
    progress: 45,
    language: 'no',
    audience: 'tech-entusiaster',
    error_message: null,
    script: null,
    created_at: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
  },
  {
    id: 'p3',
    trend_id: null,
    title: 'Top 10 VS Code Extensions 2025',
    status: 'scripting',
    progress: 20,
    language: 'no',
    audience: 'utviklere',
    error_message: null,
    script: null,
    created_at: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
  },
  {
    id: 'p4',
    trend_id: null,
    title: 'Slik tjener du penger på YouTube uten å vise ansiktet',
    status: 'complete',
    progress: 100,
    language: 'no',
    audience: 'content-skapere',
    error_message: null,
    script: null,
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'p5',
    trend_id: null,
    title: 'AI erstatter disse jobbene innen 2026',
    status: 'failed',
    progress: 35,
    language: 'no',
    audience: 'general',
    error_message: 'FFMPEG rendering error: codec not found',
    script: null,
    created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
];

export const mockVideos: Video[] = [
  {
    id: 'v1',
    production_id: 'p4',
    title: 'Slik tjener du penger på YouTube uten å vise ansiktet',
    thumbnail_url: 'https://images.pexels.com/photos/3153198/pexels-photo-3153198.jpeg?auto=compress&cs=tinysrgb&w=400',
    video_url_9x16: '',
    video_url_16x9: '',
    duration: 387,
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'v2',
    production_id: 'old1',
    title: 'Morning Routine som endret livet mitt',
    thumbnail_url: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=400',
    video_url_9x16: '',
    video_url_16x9: '',
    duration: 241,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
  },
  {
    id: 'v3',
    production_id: 'old2',
    title: '5 produktivitetsapper du ikke visste om',
    thumbnail_url: 'https://images.pexels.com/photos/1181271/pexels-photo-1181271.jpeg?auto=compress&cs=tinysrgb&w=400',
    video_url_9x16: '',
    video_url_16x9: '',
    duration: 312,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 42).toISOString(),
  },
  {
    id: 'v4',
    production_id: 'old3',
    title: 'Slik lager du passive inntekter med AI i 2025',
    thumbnail_url: 'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=400',
    video_url_9x16: '',
    video_url_16x9: '',
    duration: 451,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 66).toISOString(),
  },
];

export const mockPlatforms: Platform[] = [
  { id: 'pl1', name: 'YouTube', connected: true, account_name: '@VideoMillNO', account_avatar: '' },
  { id: 'pl2', name: 'TikTok', connected: true, account_name: '@videomill', account_avatar: '' },
  { id: 'pl3', name: 'Instagram', connected: false, account_name: '', account_avatar: '' },
  { id: 'pl4', name: 'Facebook', connected: false, account_name: '', account_avatar: '' },
];

export const mockDistributions: (VideoDistribution & { videoTitle: string })[] = [
  { id: 'd1', video_id: 'v1', videoTitle: 'Slik tjener du penger på YouTube uten å vise ansiktet', platform: 'YouTube', status: 'live', external_url: '#', views: 8432, likes: 612, posted_at: new Date(Date.now() - 1000 * 60 * 40).toISOString() },
  { id: 'd2', video_id: 'v1', videoTitle: 'Slik tjener du penger på YouTube uten å vise ansiktet', platform: 'TikTok', status: 'live', external_url: '#', views: 24100, likes: 2890, posted_at: new Date(Date.now() - 1000 * 60 * 38).toISOString() },
  { id: 'd3', video_id: 'v2', videoTitle: 'Morning Routine som endret livet mitt', platform: 'YouTube', status: 'live', external_url: '#', views: 12850, likes: 940, posted_at: new Date(Date.now() - 1000 * 60 * 60 * 17).toISOString() },
  { id: 'd4', video_id: 'v2', videoTitle: 'Morning Routine som endret livet mitt', platform: 'TikTok', status: 'live', external_url: '#', views: 51200, likes: 7100, posted_at: new Date(Date.now() - 1000 * 60 * 60 * 16).toISOString() },
  { id: 'd5', video_id: 'v3', videoTitle: '5 produktivitetsapper du ikke visste om', platform: 'YouTube', status: 'live', external_url: '#', views: 3210, likes: 280, posted_at: new Date(Date.now() - 1000 * 60 * 60 * 41).toISOString() },
  { id: 'd6', video_id: 'v4', videoTitle: 'Slik lager du passive inntekter med AI i 2025', platform: 'YouTube', status: 'live', external_url: '#', views: 19400, likes: 1520, posted_at: new Date(Date.now() - 1000 * 60 * 60 * 65).toISOString() },
];

export const mockComments: (Comment & { videoTitle: string })[] = [
  { id: 'c1', video_id: 'v1', videoTitle: 'Slik tjener du penger på YouTube uten å vise ansiktet', platform: 'YouTube', author: 'TechNerd92', text: 'Fantastisk video! Kan du lage en om Faceless YouTube på norsk?', sentiment: 'positive', replied: true, reply_text: 'Takk! Ja, en mer dyptgående guide kommer neste uke!', posted_at: new Date(Date.now() - 1000 * 60 * 20).toISOString() },
  { id: 'c2', video_id: 'v1', videoTitle: 'Slik tjener du penger på YouTube uten å vise ansiktet', platform: 'TikTok', author: 'marieeriksen', text: 'Stemmen er litt robotaktig. Ellers bra innhold!', sentiment: 'neutral', replied: false, reply_text: null, posted_at: new Date(Date.now() - 1000 * 60 * 35).toISOString() },
  { id: 'c3', video_id: 'v2', videoTitle: 'Morning Routine som endret livet mitt', platform: 'YouTube', author: 'ProductivityKing', text: 'Hvilke apper bruker du for å tracke rutinen din?', sentiment: 'positive', replied: true, reply_text: 'Jeg bruker Notion og Habitica! Sjekk ut min Notion-guide for mer info.', posted_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString() },
  { id: 'c4', video_id: 'v2', videoTitle: 'Morning Routine som endret livet mitt', platform: 'TikTok', author: 'realistisk_anders', text: 'Dette funker ikke i virkeligheten. Du bare sitter foran kamera hele dagen.', sentiment: 'negative', replied: false, reply_text: null, posted_at: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString() },
  { id: 'c5', video_id: 'v4', videoTitle: 'Slik lager du passive inntekter med AI i 2025', platform: 'YouTube', author: 'investor_lars', text: 'Kan du lage en video om konkrete tall? Hva er realistisk å tjene?', sentiment: 'positive', replied: false, reply_text: null, posted_at: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString() },
];

export const mockAnalytics: { date: string; views: number; likes: number; shares: number }[] = [
  { date: '10. apr', views: 4200, likes: 380, shares: 90 },
  { date: '11. apr', views: 6800, likes: 540, shares: 140 },
  { date: '12. apr', views: 5100, likes: 420, shares: 110 },
  { date: '13. apr', views: 9400, likes: 810, shares: 220 },
  { date: '14. apr', views: 12800, likes: 1120, shares: 340 },
  { date: '15. apr', views: 18200, likes: 1640, shares: 490 },
  { date: '16. apr', views: 24100, likes: 2210, shares: 670 },
];
