/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#0e0e0e",
        "on-error": "#690005",
        "primary-fixed-dim": "#2fd9f4",
        "surface-variant": "#353534",
        "tertiary-container": "#c0c1c1",
        "secondary-container": "#cf5cff",
        "surface-container-highest": "#353534",
        "inverse-primary": "#006877",
        "primary": "#8aebff",
        "surface-container": "#201f1f",
        "primary-container": "#22d3ee",
        "outline-variant": "#3c494c",
        "surface": "#131313",
        "on-tertiary-container": "#4d4f4f",
        "surface-bright": "#3a3939",
        "on-secondary-fixed": "#320047",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-secondary-fixed-variant": "#74009f",
        "on-background": "#e5e2e1",
        "on-tertiary-fixed-variant": "#454747",
        "secondary-fixed": "#f8d8ff",
        "surface-dim": "#131313",
        "on-secondary": "#520071",
        "on-surface": "#e5e2e1",
        "error-container": "#93000a",
        "secondary": "#ecb2ff",
        "on-surface-variant": "#bbc9cd",
        "tertiary-fixed": "#e2e2e2",
        "inverse-surface": "#e5e2e1",
        "surface-container-low": "#1c1b1b",
        "error": "#ffb4ab",
        "surface-tint": "#2fd9f4",
        "on-primary-container": "#005763",
        "outline": "#859397",
        "on-tertiary-fixed": "#1a1c1c",
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#001f25",
        "surface-container-high": "#2a2a2a",
        "primary-fixed": "#a2eeff",
        "background": "#131313",
        "inverse-on-surface": "#313030",
        "on-primary-fixed-variant": "#004e5a",
        "tertiary": "#dcdddd",
        "on-tertiary": "#2f3131",
        "secondary-fixed-dim": "#ecb2ff",
        "on-secondary-container": "#480063",
        "on-primary": "#00363e"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "body-lg": ["Epilogue", "sans-serif"],
        "body-md": ["Epilogue", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
      },
      animation: {
        'spin-slow': 'spin 12s linear infinite',
        'pulse-fast': 'pulse 1s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      }
    },
  },
  plugins: [],
}
